In [1]:
import numpy as np

In [4]:
a=np.random.randn((10))

In [5]:
b=np.random.randn((10))

In [6]:
a

array([-0.18800542, -0.79377033,  0.62471611, -0.1647785 , -2.04247867,
       -0.45231425, -0.52226816, -0.77640461,  0.09107242,  0.56535269])

In [7]:
b

array([ 1.16969918, -0.7435026 ,  1.04194802, -2.41304774,  1.94855116,
        1.66036362,  0.25171229, -0.50040898,  0.1935871 ,  0.96064919])

In [8]:
a+b

array([ 0.98169376, -1.53727293,  1.66666413, -2.57782624, -0.09392751,
        1.20804938, -0.27055587, -1.27681358,  0.28465953,  1.52600188])

In [9]:
a-b

array([-1.3577046 , -0.05026773, -0.41723191,  2.24826924, -3.99102983,
       -2.11267787, -0.77398045, -0.27599563, -0.10251468, -0.39529649])

In [11]:
a>0

array([False, False,  True, False, False, False, False, False,  True,
        True])

In [12]:
a[a>0]

array([0.62471611, 0.09107242, 0.56535269])

# indexing siling

In [24]:
x=np.array([1,4,6,7,8,9,0])

In [25]:
x[4]

8

In [26]:
x[x>4]

array([6, 7, 8, 9])

In [27]:
x[[2,1]]

array([6, 4])

In [36]:
a=np.random.randn(10,10)

In [37]:
a

array([[-1.05642887,  2.06240411, -0.58046688,  0.0676796 ,  0.36133065,
         1.04095995, -2.53602706,  0.64477844, -0.83555095,  0.61901313],
       [ 0.80463699,  0.75940579,  0.24671168,  1.07206004,  0.45916536,
         0.90221919, -0.74077421, -1.34881768, -0.17983312,  0.30065721],
       [ 0.74495532, -0.48401155, -1.14322044, -2.09754289,  1.00884116,
        -1.15750343,  1.259962  ,  1.22469346, -1.18716503,  1.06386291],
       [ 0.04972035, -0.88427855,  0.8537326 ,  2.25880681, -1.03028092,
        -0.29004835,  0.73676504,  0.6527486 ,  1.52079359,  0.25947353],
       [-0.52954352, -0.73264061, -0.13365847,  1.21867079,  1.26915518,
        -0.0483056 , -1.87800204, -2.03791102, -1.4124542 ,  0.10935083],
       [ 0.64500623, -0.17847225, -1.21930707, -0.94866177, -0.33228384,
        -1.57395604, -0.07540212, -0.27968801,  1.19259696,  0.7260572 ],
       [ 0.02889998,  0.43535669, -0.1247849 ,  0.13045252, -1.2068781 ,
        -0.92158831,  0.27731689, -0.16865304

In [38]:
a[0]

array([-1.05642887,  2.06240411, -0.58046688,  0.0676796 ,  0.36133065,
        1.04095995, -2.53602706,  0.64477844, -0.83555095,  0.61901313])

In [39]:
a[0][4]

0.36133065058040936

In [40]:
a[1:10:2]

array([[ 0.80463699,  0.75940579,  0.24671168,  1.07206004,  0.45916536,
         0.90221919, -0.74077421, -1.34881768, -0.17983312,  0.30065721],
       [ 0.04972035, -0.88427855,  0.8537326 ,  2.25880681, -1.03028092,
        -0.29004835,  0.73676504,  0.6527486 ,  1.52079359,  0.25947353],
       [ 0.64500623, -0.17847225, -1.21930707, -0.94866177, -0.33228384,
        -1.57395604, -0.07540212, -0.27968801,  1.19259696,  0.7260572 ],
       [-2.41257757,  1.54021563,  2.18095903,  1.516422  , -0.13628389,
         0.77893254,  0.73017068,  0.54062022, -0.4582966 ,  0.98324003],
       [-0.16542802,  1.23700532,  1.42084462, -0.53758236,  1.00800595,
         1.04260889, -1.43967496, -1.01285206,  1.05226616,  0.54690254]])

In [43]:
a[::,0:4]

array([[-1.05642887,  2.06240411, -0.58046688,  0.0676796 ],
       [ 0.80463699,  0.75940579,  0.24671168,  1.07206004],
       [ 0.74495532, -0.48401155, -1.14322044, -2.09754289],
       [ 0.04972035, -0.88427855,  0.8537326 ,  2.25880681],
       [-0.52954352, -0.73264061, -0.13365847,  1.21867079],
       [ 0.64500623, -0.17847225, -1.21930707, -0.94866177],
       [ 0.02889998,  0.43535669, -0.1247849 ,  0.13045252],
       [-2.41257757,  1.54021563,  2.18095903,  1.516422  ],
       [-1.18174878, -0.68629181,  1.1839087 ,  1.05392595],
       [-0.16542802,  1.23700532,  1.42084462, -0.53758236]])

In [44]:
b=np.ones((5,5))

In [45]:
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
b[1:-1,1:-1]=0

In [47]:
b

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# function

In [49]:
d=np.array([10,9,6,8,7])

In [51]:
np.sqrt(d)

array([3.16227766, 3.        , 2.44948974, 2.82842712, 2.64575131])

In [52]:
np.power(d,2)

array([100,  81,  36,  64,  49], dtype=int32)

In [55]:
y=[4,3,2,5,-1]

In [60]:
np.maximum(y,d)

array([10,  9,  6,  8,  7])