In [11]:
import numpy as np

In [12]:
salary=np.array([0,-1,10000,150000])

In [13]:
np.where(salary<=0,20000,salary)

array([ 20000,  20000,  10000, 150000])

In [14]:
np.where(salary<=0,"not ok","ok")

array(['not ok', 'not ok', 'ok', 'ok'], dtype='<U6')

# statiscal

In [24]:
x=np.array([10,9,8,10,7,6])

In [25]:
x.mean()

8.333333333333334

In [26]:
x.cumsum()

array([10, 19, 27, 37, 44, 50], dtype=int32)

In [27]:
x.cumprod()

array([    10,     90,    720,   7200,  50400, 302400], dtype=int32)

In [28]:
y=x>6

In [29]:
y

array([ True,  True,  True,  True,  True, False])

In [30]:
y.sum()

5

In [31]:
y.any()

True

In [32]:
y.all()

False

In [33]:
y=x>7

In [34]:
y

array([ True,  True,  True,  True, False, False])

In [35]:
y.sum()

4

In [36]:
x

array([10,  9,  8, 10,  7,  6])

In [37]:
x.sort()

In [38]:
x

array([ 6,  7,  8,  9, 10, 10])

In [42]:
np.unique(x)

array([ 6,  7,  8,  9, 10])

# filing

In [17]:
import numpy as np

In [18]:
s=[1,3,4,6,7]

In [19]:
e=[7,8,9,10]

In [20]:
np.save("tests",s)

In [21]:
loads=np.load("tests.npy")

In [22]:
loads

array([1, 3, 4, 6, 7])

In [23]:
np.savez("testse",s,e)

In [25]:
loadse=np.load("testse.npz")

In [26]:
loadse

# linear algebra

In [29]:
import numpy as np

In [30]:
x=np.random.randn(3,2)

In [31]:
y=np.random.randn(2,3)

In [32]:
x.dot(y)

array([[-0.12221532, -0.1148204 ,  0.22745381],
       [-0.22002975, -0.34034348, -0.00687866],
       [-0.16569988, -0.25819674, -0.01107265]])

In [33]:
x.transpose()

array([[-0.0765446 , -0.54447216, -0.41578586],
       [-0.55900482, -0.27720002, -0.19843405]])

In [34]:
x.trace()

-0.3537446171808109

# random

In [2]:
import numpy as np

In [3]:
np.random.seed(7)

In [5]:
np.random.normal(size=(3,3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

In [7]:
np.random.uniform(size=(3,4))

array([[0.38094113, 0.06593635, 0.2881456 , 0.90959353],
       [0.21338535, 0.45212396, 0.93120602, 0.02489923],
       [0.60054892, 0.9501295 , 0.23030288, 0.54848992]])